apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Olasunkanmi-O/e-commerce-helm'
    targetRevision: main
    path: adservice
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

